/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/replays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List replays */
        get: operations["GetApiReplays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replays/{matchID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full analysis for a replay */
        get: operations["GetApiReplaysByMatchID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        Color: {
            r: number;
            g: number;
            b: number;
        };
        Player: {
            /** @description 1-based player ID; matches cmd <P> */
            id: number;
            name: string;
            civ: string;
            team: number;
            is_ai: boolean;
            ai_diff?: number;
            color: components["schemas"]["Color"];
        };
        ReplaySummary: {
            match_id: string;
            map: string;
            /** Format: int64 */
            timestamp: number;
            /** Format: int64 */
            duration_ms: number;
            players: components["schemas"]["Player"][];
            outcome: string;
        };
        GameInfo: {
            match_id: string;
            map: string;
            map_type: string;
            /**
             * Format: int64
             * @description Unix seconds
             */
            timestamp: number;
            /** Format: int64 */
            duration_ms: number;
            engine_version: string;
            victory_conditions: string[];
        };
        Event: {
            /**
             * Format: int64
             * @description Milliseconds from game start
             */
            t: number;
            /** @description 1-based player ID */
            player: number;
            type: string;
            data?: unknown;
        };
        Snapshot: Record<string, never>;
        Resources: {
            food: number;
            wood: number;
            stone: number;
            metal: number;
        };
        PlayerFinalState: {
            phase: string;
            /** @description active | won | defeated */
            state: string;
            /** @description Resolved outcome; resign event takes precedence */
            outcome: string;
            pop_count: number;
            pop_limit: number;
            pop_max: number;
            resource_counts: components["schemas"]["Resources"];
            researched_techs: string[];
        };
        FinalState: {
            /** @description Keyed by player ID as string */
            players: {
                [key: string]: components["schemas"]["PlayerFinalState"];
            };
        };
        Engagement: {
            t_start_sec: number;
            t_end_sec: number;
            target: number;
            peak_units: number;
            command_count: number;
        };
        Anomaly: {
            type: string;
            t_start_sec: number;
            t_end_sec: number;
            severity: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /** @description Per-class cumulative time-series. Each array aligns to Sequences.time. */
        ClassSeriesMap: {
            [key: string]: number[];
        };
        /** @description Per-resource time-series. Keys: food, wood, stone, metal (and possibly vegetarianFood). */
        ResourceSeriesMap: {
            [key: string]: number[];
        };
        Sequences: {
            /** @description X-axis, seconds from game start (~30s sampling) */
            time: number[];
            population_count: number[];
            percent_map_explored: number[];
            percent_map_controlled: number[];
            units_trained: components["schemas"]["ClassSeriesMap"];
            units_lost: components["schemas"]["ClassSeriesMap"];
            enemy_units_killed: components["schemas"]["ClassSeriesMap"];
            units_captured: components["schemas"]["ClassSeriesMap"];
            buildings_constructed: components["schemas"]["ClassSeriesMap"];
            buildings_lost: components["schemas"]["ClassSeriesMap"];
            enemy_buildings_destroyed: components["schemas"]["ClassSeriesMap"];
            buildings_captured: components["schemas"]["ClassSeriesMap"];
            units_lost_value: number[];
            enemy_units_killed_value: number[];
            units_captured_value: number[];
            buildings_lost_value: number[];
            enemy_buildings_destroyed_value: number[];
            buildings_captured_value: number[];
            trade_income: number[];
            tributes_sent: number[];
            tributes_received: number[];
            loot_collected: number[];
            treasures_collected: number[];
            successful_bribes: number[];
            failed_bribes: number[];
            resources_count: components["schemas"]["ResourceSeriesMap"];
            resources_gathered: components["schemas"]["ResourceSeriesMap"];
            resources_used: components["schemas"]["ResourceSeriesMap"];
            resources_bought: components["schemas"]["ResourceSeriesMap"];
            resources_sold: components["schemas"]["ResourceSeriesMap"];
        };
        ImprovementCost: {
            food?: number;
            wood?: number;
            stone?: number;
            metal?: number;
        };
        ImprovementEntry: {
            /** Format: int64 */
            t_ms: number;
            template: string;
            generic_name?: string;
            description?: string;
            building?: string;
            buildings?: string[];
            cost?: components["schemas"]["ImprovementCost"];
            /** Format: double */
            research_time?: number;
            auto_research?: boolean;
        };
        PlayerMetrics: {
            /** @description Phase name to seconds when it was reached */
            phase_timings: {
                [key: string]: number;
            };
            engagements: components["schemas"]["Engagement"][];
            anomalies: components["schemas"]["Anomaly"][];
            sequences?: components["schemas"]["Sequences"];
            improvements: components["schemas"]["ImprovementEntry"][];
        };
        Metrics: {
            /** @description Keyed by player ID as string */
            players: {
                [key: string]: components["schemas"]["PlayerMetrics"];
            };
        };
        Analysis: {
            schema_version: number;
            game: components["schemas"]["GameInfo"];
            players: components["schemas"]["Player"][];
            events: components["schemas"]["Event"][];
            snapshots: components["schemas"]["Snapshot"][];
            final_state: components["schemas"]["FinalState"];
            metrics: components["schemas"]["Metrics"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetApiReplays: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of replay summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplaySummary"][];
                };
            };
        };
    };
    GetApiReplaysByMatchID: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Replay not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
