// Package sandbox reads sequences from metadata.json files regenerated by
// running `pyrogenesis -replay=<commands.txt> -userdir=<sandbox-dir>` headless.
// The sandbox dir lives outside the user's real 0 A.D. replay directory so
// the original commands.txt + metadata.json stay untouched.
package sandbox

import (
	"encoding/json"
	"os"
	"path/filepath"

	"github.com/ZetoOfficial/0ad-civ-report-parser/internal/replay/output"
)

// DefaultRoot is the path under which Load looks for regenerated replays.
// Layout mirrors a 0 A.D. user dir: <DefaultRoot>/replays/0.28.0/<basename>/metadata.json
const DefaultRoot = "/tmp/0ad-replay-sandbox"

// Load reads sequences for each player from the sandbox metadata.json that
// corresponds to replayBasename (e.g. "2026-05-28_0001"). Returns map keyed by
// 1-based player ID. Returns nil (no error) if the file is missing or empty —
// callers treat this as "no sequences yet for this replay".
//
// Note: schema produced by pyrogenesis 0.28 uses camelCase field names; we
// unmarshal into a private mirror type and convert to our snake_case output
// types.
func Load(replayBasename string) (map[int]*output.Sequences, error) {
	return LoadFromRoot(DefaultRoot, replayBasename)
}

// LoadFromRoot is Load with a custom sandbox root (test seam).
func LoadFromRoot(root, replayBasename string) (map[int]*output.Sequences, error) {
	path := filepath.Join(root, "replays", "0.28.0", replayBasename, "metadata.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	if len(raw) == 0 {
		return nil, nil
	}
	return Parse(raw)
}

// Parse decodes the metadata.json bytes and returns per-player sequences.
// Skips player 0 (gaia) and any player whose sequences key is missing.
func Parse(raw []byte) (map[int]*output.Sequences, error) {
	var doc struct {
		PlayerStates []rawPlayer `json:"playerStates"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, err
	}
	out := map[int]*output.Sequences{}
	for i, ps := range doc.PlayerStates {
		if i == 0 {
			continue // gaia
		}
		if ps.Sequences == nil {
			continue
		}
		s := convert(ps.Sequences)
		if s == nil {
			continue
		}
		out[i] = s
	}
	if len(out) == 0 {
		return nil, nil
	}
	return out, nil
}

type rawPlayer struct {
	Sequences *rawSequences `json:"sequences"`
}

type rawSequences struct {
	Time                      []float64           `json:"time"`
	PopulationCount           []int               `json:"populationCount"`
	PercentMapExplored        []int               `json:"percentMapExplored"`
	PercentMapControlled      []int               `json:"percentMapControlled"`
	UnitsTrained              map[string][]int    `json:"unitsTrained"`
	UnitsLost                 map[string][]int    `json:"unitsLost"`
	EnemyUnitsKilled          map[string][]int    `json:"enemyUnitsKilled"`
	UnitsCaptured             map[string][]int    `json:"unitsCaptured"`
	BuildingsConstructed      map[string][]int    `json:"buildingsConstructed"`
	BuildingsLost             map[string][]int    `json:"buildingsLost"`
	EnemyBuildingsDestroyed   map[string][]int    `json:"enemyBuildingsDestroyed"`
	BuildingsCaptured         map[string][]int    `json:"buildingsCaptured"`
	UnitsLostValue           []float64 `json:"unitsLostValue"`
	EnemyUnitsKilledValue    []float64 `json:"enemyUnitsKilledValue"`
	UnitsCapturedValue       []float64 `json:"unitsCapturedValue"`
	BuildingsLostValue       []float64 `json:"buildingsLostValue"`
	EnemyBuildingsDestroyVal []float64 `json:"enemyBuildingsDestroyedValue"`
	BuildingsCapturedValue   []float64 `json:"buildingsCapturedValue"`
	TradeIncome              []float64 `json:"tradeIncome"`
	TributesSent             []float64 `json:"tributesSent"`
	TributesReceived         []float64 `json:"tributesReceived"`
	LootCollected            []float64 `json:"lootCollected"`
	TreasuresCollected       []float64 `json:"treasuresCollected"`
	SuccessfulBribes         []int     `json:"successfulBribes"`
	FailedBribes             []int     `json:"failedBribes"`

	ResourcesCount    map[string][]float64 `json:"resourcesCount"`
	ResourcesGathered map[string][]float64 `json:"resourcesGathered"`
	ResourcesUsed     map[string][]float64 `json:"resourcesUsed"`
	ResourcesBought   map[string][]float64 `json:"resourcesBought"`
	ResourcesSold     map[string][]float64 `json:"resourcesSold"`
}

func convert(r *rawSequences) *output.Sequences {
	if len(r.Time) == 0 {
		return nil
	}
	return &output.Sequences{
		Time:                     r.Time,
		PopulationCount:          r.PopulationCount,
		PercentMapExplored:       r.PercentMapExplored,
		PercentMapControlled:     r.PercentMapControlled,
		UnitsTrained:             output.ClassSeries(r.UnitsTrained),
		UnitsLost:                output.ClassSeries(r.UnitsLost),
		EnemyUnitsKilled:         output.ClassSeries(r.EnemyUnitsKilled),
		UnitsCaptured:            output.ClassSeries(r.UnitsCaptured),
		BuildingsConstructed:     output.ClassSeries(r.BuildingsConstructed),
		BuildingsLost:            output.ClassSeries(r.BuildingsLost),
		EnemyBuildingsDestroy:    output.ClassSeries(r.EnemyBuildingsDestroyed),
		BuildingsCaptured:        output.ClassSeries(r.BuildingsCaptured),
		UnitsLostValue:           r.UnitsLostValue,
		EnemyUnitsKilledValue:    r.EnemyUnitsKilledValue,
		UnitsCapturedValue:       r.UnitsCapturedValue,
		BuildingsLostValue:       r.BuildingsLostValue,
		EnemyBuildingsDestroyVal: r.EnemyBuildingsDestroyVal,
		BuildingsCapturedValue:   r.BuildingsCapturedValue,
		TradeIncome:              r.TradeIncome,
		TributesSent:             r.TributesSent,
		TributesReceived:         r.TributesReceived,
		LootCollected:            r.LootCollected,
		TreasuresCollected:       r.TreasuresCollected,
		SuccessfulBribes:         r.SuccessfulBribes,
		FailedBribes:             r.FailedBribes,
		ResourcesCount:           output.ResourceSeries(r.ResourcesCount),
		ResourcesGathered:        output.ResourceSeries(r.ResourcesGathered),
		ResourcesUsed:            output.ResourceSeries(r.ResourcesUsed),
		ResourcesBought:          output.ResourceSeries(r.ResourcesBought),
		ResourcesSold:            output.ResourceSeries(r.ResourcesSold),
	}
}
