package render

import (
	"fmt"
	"strings"

	"github.com/ZetoOfficial/0ad-civ-report-parser/internal/i18n"
	"github.com/ZetoOfficial/0ad-civ-report-parser/internal/tech"
)

// renderCommonBody returns the body of common.md (without the skeleton
// wrapper). Sections, in order:
//  1. Модификаторы Advanced
//  2. Модификаторы Elite
//  3. Прочие глобальные авто-эффекты
//  4. Типы урона
//  5. Типы ресурсов
//  6. Статус-эффекты
//
// All section titles render at "## " level so anchors generated by
// GitHub-style markdown work for cross-file links from civ overviews.
func (g *Generator) renderCommonBody() (string, error) {
	var sb strings.Builder
	if err := g.commonAdvanced(&sb); err != nil {
		return "", err
	}
	if err := g.commonElite(&sb); err != nil {
		return "", err
	}
	if err := g.commonOtherAuto(&sb); err != nil {
		return "", err
	}
	if err := g.commonDamageTypes(&sb); err != nil {
		return "", err
	}
	if err := g.commonResources(&sb); err != nil {
		return "", err
	}
	if err := g.commonStatusEffects(&sb); err != nil {
		return "", err
	}
	return sb.String(), nil
}

func (g *Generator) commonAdvanced(sb *strings.Builder) error {
	t, err := g.Catalog.ByName("unit_advanced")
	if err != nil {
		return err
	}
	fmt.Fprintln(sb, "## Модификаторы Advanced")
	fmt.Fprintln(sb)
	if t.Tooltip != "" {
		fmt.Fprintf(sb, "> %s\n\n", t.Tooltip)
	}
	commonModTable(sb, t.Modifications)
	return nil
}

func (g *Generator) commonElite(sb *strings.Builder) error {
	t, err := g.Catalog.ByName("unit_elite")
	if err != nil {
		return err
	}
	fmt.Fprintln(sb, "## Модификаторы Elite")
	fmt.Fprintln(sb)
	if t.Tooltip != "" {
		fmt.Fprintf(sb, "> %s\n\n", t.Tooltip)
	}
	commonModTable(sb, t.Modifications)
	return nil
}

func (g *Generator) commonOtherAuto(sb *strings.Builder) error {
	all, err := g.Catalog.GlobalAutoResearch()
	if err != nil {
		return err
	}
	others := []*tech.Technology{}
	for _, t := range all {
		if t.Name == "unit_advanced" || t.Name == "unit_elite" {
			continue
		}
		others = append(others, t)
	}
	fmt.Fprintln(sb, "## Прочие глобальные авто-эффекты")
	fmt.Fprintln(sb)
	if len(others) == 0 {
		fmt.Fprintln(sb, "*В текущих данных только Advanced/Elite.*")
		fmt.Fprintln(sb)
		return nil
	}
	fmt.Fprintln(sb, "Сюда попадают autoResearch-техи без `requirements.civ`,")
	fmt.Fprintln(sb, "не относящиеся к ранговому апгрейду:")
	fmt.Fprintln(sb)
	for _, t := range others {
		name := t.GenericName
		if name == "" {
			name = t.Name
		}
		fmt.Fprintf(sb, "### %s (`%s`)\n\n", name, t.Name)
		if t.Tooltip != "" {
			fmt.Fprintf(sb, "> %s\n\n", t.Tooltip)
		} else if t.Description != "" {
			fmt.Fprintf(sb, "> %s\n\n", t.Description)
		}
		if len(t.Modifications) > 0 {
			commonModTable(sb, t.Modifications)
		}
	}
	return nil
}

func commonModTable(sb *strings.Builder, mods []tech.Modification) {
	if len(mods) == 0 {
		fmt.Fprintln(sb, "*Нет модификаций.*")
		fmt.Fprintln(sb)
		return
	}
	fmt.Fprintln(sb, "| Цель | Эффект |")
	fmt.Fprintln(sb, "|------|--------|")
	for _, m := range mods {
		fmt.Fprintf(sb, "| %s | %s |\n",
			escapeTable(m.Value),
			escapeTable(i18n.DescribeModification(m)))
	}
	fmt.Fprintln(sb)
}

func (g *Generator) commonDamageTypes(sb *strings.Builder) error {
	dts, err := loadDamageTypes(g.Layout.DamageTypes())
	if err != nil {
		return err
	}
	fmt.Fprintln(sb, "## Типы урона")
	fmt.Fprintln(sb)
	fmt.Fprintln(sb, "| Код | Имя | Описание |")
	fmt.Fprintln(sb, "|-----|-----|----------|")
	for _, d := range dts {
		fmt.Fprintf(sb, "| `%s` | %s | %s |\n",
			d.Code, escapeTable(d.Name), escapeTable(d.Description))
	}
	fmt.Fprintln(sb)
	return nil
}

func (g *Generator) commonResources(sb *strings.Builder) error {
	rs, err := loadResources(g.Layout.Resources())
	if err != nil {
		return err
	}
	fmt.Fprintln(sb, "## Типы ресурсов")
	fmt.Fprintln(sb)
	fmt.Fprintln(sb, "| Код | Имя | Описание |")
	fmt.Fprintln(sb, "|-----|-----|----------|")
	for _, r := range rs {
		fmt.Fprintf(sb, "| `%s` | %s | %s |\n",
			r.Code, escapeTable(r.Name), escapeTable(r.Description))
	}
	fmt.Fprintln(sb)
	hasSubtypes := false
	for _, r := range rs {
		if len(r.Subtypes) > 0 {
			hasSubtypes = true
			break
		}
	}
	if hasSubtypes {
		fmt.Fprintln(sb, "### Подтипы ресурсов")
		fmt.Fprintln(sb)
		for _, r := range rs {
			if len(r.Subtypes) == 0 {
				continue
			}
			fmt.Fprintf(sb, "- **%s**: %s\n", r.Code, joinSubtypes(r))
		}
		fmt.Fprintln(sb)
	}
	return nil
}

func (g *Generator) commonStatusEffects(sb *strings.Builder) error {
	es, err := loadStatusEffects(g.Layout.StatusEffects())
	if err != nil {
		return err
	}
	fmt.Fprintln(sb, "## Статус-эффекты")
	fmt.Fprintln(sb)
	fmt.Fprintln(sb, "| Код | Имя | На применяющего | На пострадавшего |")
	fmt.Fprintln(sb, "|-----|-----|-----------------|------------------|")
	for _, e := range es {
		fmt.Fprintf(sb, "| `%s` | %s | %s | %s |\n",
			e.Code, escapeTable(e.StatusName),
			escapeTable(e.ApplierTooltip), escapeTable(e.ReceiverTooltip))
	}
	fmt.Fprintln(sb)
	// Per-status sub-blocks with anchors for cross-file links.
	// GitHub auto-lowercases heading anchors: ### Poisoned → #poisoned.
	for _, e := range es {
		fmt.Fprintf(sb, "### %s\n\n", e.StatusName)
		if e.ApplierTooltip != "" {
			fmt.Fprintf(sb, "> **Применяющему:** %s\n", e.ApplierTooltip)
		}
		if e.ReceiverTooltip != "" {
			fmt.Fprintf(sb, "> **Пострадавшему:** %s\n", e.ReceiverTooltip)
		}
		fmt.Fprintln(sb)
	}
	return nil
}
